name: Synchronize Remote Repositories
on:
  push:
    branches:
      - master
      - revamp-github-actions

jobs:
  mirror:
    name: Synchronize Mirror Repository
    runs-on: ubuntu-latest
    env:
      CI: 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.MIRROR_REPO_SSH_KEY }}
      - name: Set up Git
        run: |
          git remote add mirror "$REMOTE"
          git fetch mirror master
        env:
          REMOTE: ${{ secrets.MIRROR_REPO_GIT_REMOTE }}
      - run: git branch
      - run: git show HEAD
      - run: git show origin/master
      - run: git show mirror/master
      - run: git diff --stat origin/master...mirror/master
      - run: git diff --stat HEAD...origin/master
      - run: git diff --stat HEAD...mirror/master
      - run: |
          echo zomg > hi.txt
          git config --global user.email "engineering@tilde.io"
          git config --global user.name "Tilde Engineering"
          git add hi.txt
          git commit -m "wow"
      - run: git branch
      - run: git show HEAD
      - run: git show origin/master
      - run: git show mirror/master
      - run: git diff --stat origin/master...mirror/master
      - run: git diff --stat HEAD...origin/master
      - run: git diff --stat HEAD...mirror/master
      - name: Push
        run: git push --dry-run mirror master
